# Generated by Django 4.1.5 on 2023-01-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_skills_location_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='skills',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='skills',
            field=models.ManyToManyField(to='app.skills'),
        ),
    ]
