# Generated by Django 4.1.5 on 2023-01-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_location_skills_jobpost_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='type',
            field=models.CharField(default='Full Time', max_length=200),
            preserve_default=False,
        ),
    ]
