# Generated by Django 4.1.5 on 2023-01-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_jobpost_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='type',
            field=models.CharField(default='Full Time', max_length=200, null=True),
        ),
    ]
